### ISSUE TITLE
When handling frontend js files, some files got JSONDecodeError error

### ISSUE THREAD

**Issue by yp05327** [DragonMinded/bemaniutils#1]
At first, to use the frontend, may be it is necessary to install NodeJs?
If it is not installed, an error will occur.

And then I installed NodeJs, try to run the frontend server and start to goto the local website.
I found these js files can't be handled:
checkbox.react.js
nav.react.js
table.react.js

error log:
127.0.0.1 - - [11/Apr/2020 18:10:43] "[35m[1mGET /jsx/components/table.react.js HTTP/1.1[0m" 500 -
Traceback (most recent call last):
  File "C:\Users\57695\AppData\Local\Programs\Python\Python37\lib\site-packages\flask\app.py", line 2463, in __call__
    return self.wsgi_app(environ, start_response)
  File "C:\Users\57695\AppData\Local\Programs\Python\Python37\lib\site-packages\flask\app.py", line 2449, in wsgi_app
    response = self.handle_exception(e)
  File "C:\Users\57695\AppData\Local\Programs\Python\Python37\lib\site-packages\flask\app.py", line 1866, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "C:\Users\57695\AppData\Local\Programs\Python\Python37\lib\site-packages\flask\_compat.py", line 39, in reraise
    raise value
  File "C:\Users\57695\AppData\Local\Programs\Python\Python37\lib\site-packages\flask\app.py", line 2446, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\57695\AppData\Local\Programs\Python\Python37\lib\site-packages\flask\app.py", line 1951, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\57695\AppData\Local\Programs\Python\Python37\lib\site-packages\flask\app.py", line 1820, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "C:\Users\57695\AppData\Local\Programs\Python\Python37\lib\site-packages\flask\_compat.py", line 39, in reraise
    raise value
  File "C:\Users\57695\AppData\Local\Programs\Python\Python37\lib\site-packages\flask\app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\57695\AppData\Local\Programs\Python\Python37\lib\site-packages\flask\app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "D:\program\bemaniutils-master\bemani\frontend\app.py", line 109, in decoratedfunction
    response = func(*args, **kwargs)
  File "D:\program\bemaniutils-master\bemani\frontend\app.py", line 127, in jsx
    jsx = transformer.transform_string(f.read())
  File "C:\Users\57695\AppData\Local\Programs\Python\Python37\lib\site-packages\react\jsx.py", line 43, in transform_string
    '%s.transform' % self.JSX_TRANSFORMER_JS_EXPR, jsx, opts)
  File "C:\Users\57695\AppData\Local\Programs\Python\Python37\lib\site-packages\execjs\_abstract_runtime_context.py", line 37, in call
    return self._call(name, *args)
  File "C:\Users\57695\AppData\Local\Programs\Python\Python37\lib\site-packages\execjs\_external_runtime.py", line 92, in _call
    return self._eval("{identifier}.apply(this, {args})".format(identifier=identifier, args=args))
  File "C:\Users\57695\AppData\Local\Programs\Python\Python37\lib\site-packages\execjs\_external_runtime.py", line 78, in _eval
    return self.exec_(code)
  File "C:\Users\57695\AppData\Local\Programs\Python\Python37\lib\site-packages\execjs\_abstract_runtime_context.py", line 18, in exec_
    return self._exec_(source)
  File "C:\Users\57695\AppData\Local\Programs\Python\Python37\lib\site-packages\execjs\_external_runtime.py", line 88, in _exec_
    return self._extract_result(output)
  File "C:\Users\57695\AppData\Local\Programs\Python\Python37\lib\site-packages\execjs\_external_runtime.py", line 159, in _extract_result
    ret = json.loads(output_last_line)
  File "C:\Users\57695\AppData\Local\Programs\Python\Python37\lib\json\__init__.py", line 348, in loads
    return _default_decoder.decode(s)
  File "C:\Users\57695\AppData\Local\Programs\Python\Python37\lib\json\decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "C:\Users\57695\AppData\Local\Programs\Python\Python37\lib\json\decoder.py", line 353, in raw_decode
    obj, end = self.scan_once(s, idx)
json.decoder.JSONDecodeError: Expecting ',' delimiter: line 1 column 2576 (char 2575)

All python libraries are latest version.
And this error also occurs in Python 3.6

**Comment by DragonMinded** [comment]
The readme states the following:

"In order to run the frontend, Python will need to find a javascript runtime. This is so it can precompile react components at render time so there doesn't need to be a compile step when developing. I found it absolutely bonkers that the backend could be on-the-fly reloaded but I had to go through an entire build process to produce interpreted JS code, so I went the route of self-contained services instead. Installing a JS runtime is also outside the scope of this document, but a quick way to get started is to install node.js."

So, this is expected.

**Comment by yp05327** [comment]
I installed node.js., but this error didn't fixed.
I found this reason is caused by html unicodes in these js files.
I changed these unicodes to english word, for example   &#9745;  changes to   checked   , then this error fixed.

I tried to find out what is different between using unicodes and no unicodes.
execjs\_external_runtime.py line 159:
ret = json.loads(output_last_line)

Where the error will be occured. So i checked the value of 'output_last_line'.
When i use unicodes, you will see some thing like this: (nav.react.js line 15)
me: \\"alert\\"}, \\"鈿燶") :\\n
but the currect value must be:
me: \\"alert\\"}, \\"鈿燶\\") :\\n
missing a '\\' there

I don't know why this happened, but i found two temporary measures to fix this.
change html unicodes code to other things
or
rewrite execjs\_external_runtime.py to support unicodes

**Comment by DragonMinded** [comment]
Ah, good catch. What is your locale setting? I bet it is not UTF-8. The JSX transformer endpoint uses the default locale, instead of reading as bytes and decoding as UTF-8. I think that a fix is possible.

**Comment by DragonMinded** [comment]
Please see if https://github.com/DragonMinded/bemaniutils/pull/6 is a possible fix?

**Comment by yp05327** [comment]
I tried to use chardet.detect to get the encoding type of table.react.js and it returns 'ascii'? not 'utf-8'

Code is changed like this:
```
with open(jsxfile, 'rb') as f:  
            transformer = JSXTransformer()  
            data = f.read()  
            chardetData = chardet.detect(data) # chardetData['encoding'] = 'ascii'  
            jsx = transformer.transform_string(data.decode('utf-8')) 
```
But it doesn't working. Also Lost a '\' in output_last_line.

Result:
A part of input:
```
data = 'sort = <span className="sort"> &#8593;</span>'
```
A part of output:
```
output_last_line = 'sort = React.createElement(\"span\", {className: \"sort\"}, \" 鈫慭");\r\n'
output_last_line.encode('utf-8') = b'sort = React.createElement(\\"span\\", {className: \\"sort\\"}, \\" \xe9\x88\xab\xe6\x85\xad");\\r\\n'
```
missing a '\\' after '\xad'

Is this value returned by node.js? Maybe this error is casued by node.js not python code?
Or i need to setup node.js/environment?

About node.js:
Then i tried to update my node.js v12.16.1 to the lastest LTS version v12.18.3, and it sill doesn't work.
Im not familiar with node.js, maybe i need to change some settings like encode?decode?
About environment:
My os language is not english, and it is hard for me to check other languages now. So can you check the output value (variable 'output_last_line' at nav.react.js line 15) in your computer? (maybe your os language is english?) And if knows the correct value of this variable, maybe it will help to solve this problem?

**Comment by DragonMinded** [comment]
I took another stab at trying to fix this. I still cannot replicate, and I think it has something to do with non-utf8 systems with reach component translation. The resulting JSX files after translation have the actual unicode characters in them, not an escape sequence. So, I replaced those instances with JSX templates containing escaped unicode JS strings. I think this might help since your system will not try to print bad characters. See https://github.com/DragonMinded/bemaniutils/commit/68c1b7cc637b896386e7d06199712d6d84f59bcd for details. Please let me know if this works.

When translating on my system before translation it looks like:

```
<span>{ "\u2713" }</span>
```

and after it looks like:

```
React.createElement("span", null,  "\u2713" )
```

**Comment by yp05327** [comment]
It works now. Thanks a lot!

**Comment by DragonMinded** [comment]
Yay! Glad we could figure out how to work around node.js bugs! I'll close the issue.
