### ISSUE TITLE
Dependency issue on SQLAlchemy version <= 1.4.x

### ISSUE THREAD

**Issue by CenoX** [DragonMinded/bemaniutils#14]
It occurs error when the SQLAlchemy version upper than 1.4.x

```
Traceback (most recent call last):
  File "/home/cenox/bemaniutils/dbutils", line 10, in <module>
    runpy.run_module(f"bemani.utils.{name}", run_name="main")
  File "/home/cenox/.pyenv/versions/3.6.12/lib/python3.6/runpy.py", line 208, in run_module
    return _run_code(code, {}, init_globals, run_name, mod_spec)
  File "/home/cenox/.pyenv/versions/3.6.12/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/cenox/bemaniutils/bemani/utils/dbutils.py", line 7, in <module>
    from bemani.data import Data, DBCreateException
  File "/home/cenox/bemaniutils/bemani/data/init.py", line 1, in <module>
    from bemani.data.data import Data, DBCreateException
  File "/home/cenox/bemaniutils/bemani/data/data.py", line 14, in <module>
    from bemani.data.api.user import GlobalUserData
  File "/home/cenox/bemaniutils/bemani/data/api/user.py", line 7, in <module>
    from bemani.data.mysql.user import UserData
  File "/home/cenox/bemaniutils/bemani/data/mysql/user.py", line 11, in <module>
    from bemani.data.mysql.base import BaseData, metadata
  File "/home/cenox/bemaniutils/bemani/data/mysql/base.py", line 8, in <module>
    from sqlalchemy.engine.result import ResultProxy  # type: ignore
ImportError: cannot import name 'ResultProxy'
```

It causes that cannot call dbutils, and uwsgi application cannot be loaded.

Workaround: Keep SQLAlchemy version in 1.3.x
```
# on virtualenv
pip3 uninstall SQLAlchemy
pip3 install SQLAlchemy==1.3.24
deactivate
```

**Comment by CenoX** [comment]
https://github.com/DragonMinded/bemaniutils/commit/ccba50e2cfc4c4a1d9f61325919b5d50482b4b51

Oh you've been fix this issue sorry.
