### ISSUE TITLE
afputils museca/sdvx support

### ISSUE THREAD

**Issue by camprevail** [DragonMinded/bemaniutils#19]
Same error trying to `list` an ifs file from museca or sdvx. 

```
D:\Konami Data Tools\Servers\bemaniutils>python afputils list generator_get.ifs
Traceback (most recent call last):
  File "D:\Konami Data Tools\Servers\bemaniutils\afputils", line 10, in <module>
    runpy.run_module(f"bemani.utils.{name}", run_name="__main__")
  File "C:\Users\Cam\AppData\Local\Programs\Python\Python39\lib\runpy.py", line 213, in run_module
    return _run_code(code, {}, init_globals, run_name, mod_spec)
  File "C:\Users\Cam\AppData\Local\Programs\Python\Python39\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "D:\Konami Data Tools\Servers\bemaniutils\bemani\utils\afputils.py", line 836, in <module>
    sys.exit(main())
  File "D:\Konami Data Tools\Servers\bemaniutils\bemani\utils\afputils.py", line 706, in main
    renderer.add_swf(afpname, flash)
  File "D:\Konami Data Tools\Servers\bemaniutils\bemani\format\afp\render.py", line 289, in add_swf
    data.parse()
  File "D:\Konami Data Tools\Servers\bemaniutils\bemani\format\afp\swf.py", line 2065, in parse
    self.__parse(verbose)
  File "D:\Konami Data Tools\Servers\bemaniutils\bemani\format\afp\swf.py", line 2182, in __parse
    self.tags, self.frames, self.labels = self.__parse_tags(ap2_data_version, version, data, tags_offset, None)
  File "D:\Konami Data Tools\Servers\bemaniutils\bemani\format\afp\swf.py", line 1975, in __parse_tags
    tags.append(self.__parse_tag(ap2_version, afp_version, ap2data, tagid, size, tags_offset + 4, sprite, tag_to_frame[i], prefix=prefix))
KeyError: 0
```

**Comment by camprevail** [comment]
Also tested with scotto and some other games - same error. Am I just doing something wrong?

**Comment by DragonMinded** [comment]
Probably not. It looks like for starters that SDVX uses DXT5 compression in ifs files which I haven't handled (yet). I can't duplicate this exact crash, however.

**Comment by camprevail** [comment]
Hmm. Well I guess I'll try it on linux and see what happens. This traceback is from windows.

**Comment by DragonMinded** [comment]
I think its failing to index into the tag-to-frame dictionary which is used for naming bytecode function decompiles, but I'm not sure why that would be windows-specific.

**Comment by DragonMinded** [comment]
Okay, I duplicated it, it seems like there are some tags not referred to in frames, but they are still necessary for defining some structures needed to render the SWF. Not sure what's going on there, aside from perhaps the format implicitly evaluates tags before the frame that they occur in, and just doesn't use them to update the screen? I can try some stuff and see if I get them rendering.

**Comment by camprevail** [comment]
Interesting.

**Comment by DragonMinded** [comment]
Okay, give it a try now, I don't know if the animations are rendering correctly but they don't crash on invariants anymore.

**Comment by camprevail** [comment]
Cool, thanks! Seems to be working with sdvx now. (On linux. Windows can list fine, but throws a huge runtime error trying to render, but I'll just run it on linux for the time being. Something to do with multiprocessing.)

Museca however, throws this: 
```
Traceback (most recent call last):
  File "afputils", line 10, in <module>
    runpy.run_module(f"bemani.utils.{name}", run_name="__main__")
  File "/usr/lib/python3.8/runpy.py", line 210, in run_module
    return _run_code(code, {}, init_globals, run_name, mod_spec)
  File "/usr/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/home/cam/bemaniutils/bemani/utils/afputils.py", line 838, in <module>
    sys.exit(main())
  File "/home/cam/bemaniutils/bemani/utils/afputils.py", line 706, in main
    renderer.add_swf(afpname, flash)
  File "/home/cam/bemaniutils/bemani/format/afp/render.py", line 324, in add_swf
    data.parse()
  File "/home/cam/bemaniutils/bemani/format/afp/swf.py", line 2065, in parse
    self.__parse(verbose)
  File "/home/cam/bemaniutils/bemani/format/afp/swf.py", line 2182, in __parse
    self.tags, self.frames, self.labels = self.__parse_tags(ap2_data_version, version, data, tags_offset, None)
  File "/home/cam/bemaniutils/bemani/format/afp/swf.py", line 1975, in __parse_tags
    tags.append(self.__parse_tag(ap2_version, afp_version, ap2data, tagid, size, tags_offset + 4, sprite, tag_to_frame.get(i, 'orphan'), prefix=prefix))
  File "/home/cam/bemaniutils/bemani/format/afp/swf.py", line 1920, in __parse_tag
    raise Exception(f"Unimplemented tag {hex(tagid)}!")
Exception: Unimplemented tag 0x83!
```

**Comment by DragonMinded** [comment]
Oh, that's an AP2_IMAGE tag. I've never encountered a SWF with that in it before. Unimplemented tags are a hard failure to help track them down. What file were you trying it on?

**Comment by DragonMinded** [comment]
PS, what was the traceback you got with multiprocessing? I suppose I could get a windows checkout and try it myself. However, if you are not compiling the cython you're in for a bad time (very slow rendering even with the multiprocessing python code).

**Comment by camprevail** [comment]
I'm fairly confident all of museca's ifs file textures are AP2. I tried it with a few - pix_ms_sel.ifs, any one of the pix_campaign_*.ifs files, etc.  And yeah, can definitely confirm slow af rendering since I didn't compile the cython.

Anyways, the multiprocessing error on windows was this:
```
D:\Konami Data Tools\Servers\bemaniutils>python afputils list demo_title.ifs
demo_title

D:\Konami Data Tools\Servers\bemaniutils>python afputils list render --path demo_title --output test.gif demo_title.ifs
usage: afputils [-h] {extract,update,print,parseafp,decompile,parsegeo,render,list} ...
afputils: error: unrecognized arguments: --path demo_title --output test.gif demo_title.ifs

D:\Konami Data Tools\Servers\bemaniutils>python afputils render --path demo_title --output test.gif demo_title.ifs
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "C:\Users\Cam\AppData\Local\Programs\Python\Python39\lib\multiprocessing\spawn.py", line 116, in spawn_main
    exitcode = _main(fd, parent_sentinel)
  File "C:\Users\Cam\AppData\Local\Programs\Python\Python39\lib\multiprocessing\spawn.py", line 125, in _main
    prepare(preparation_data)
  File "C:\Users\Cam\AppData\Local\Programs\Python\Python39\lib\multiprocessing\spawn.py", line 236, in prepare
    _fixup_main_from_path(data['init_main_from_path'])
  File "C:\Users\Cam\AppData\Local\Programs\Python\Python39\lib\multiprocessing\spawn.py", line 287, in _fixup_main_from_path
    main_content = runpy.run_path(main_path,
  File "C:\Users\Cam\AppData\Local\Programs\Python\Python39\lib\runpy.py", line 268, in run_path
    return _run_module_code(code, init_globals, run_name,
  File "C:\Users\Cam\AppData\Local\Programs\Python\Python39\lib\runpy.py", line 97, in _run_module_code
    _run_code(code, mod_globals, init_globals,
  File "C:\Users\Cam\AppData\Local\Programs\Python\Python39\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "D:\Konami Data Tools\Servers\bemaniutils\afputils", line 10, in <module>
    runpy.run_module(f"bemani.utils.{name}", run_name="__main__")
  File "C:\Users\Cam\AppData\Local\Programs\Python\Python39\lib\runpy.py", line 213, in run_module
    return _run_code(code, {}, init_globals, run_name, mod_spec)
  File "C:\Users\Cam\AppData\Local\Programs\Python\Python39\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "D:\Konami Data Tools\Servers\bemaniutils\bemani\utils\afputils.py", line 838, in <module>
    sys.exit(main())
  File "D:\Konami Data Tools\Servers\bemaniutils\bemani\utils\afputils.py", line 802, in main
    images = list(renderer.render_path(args.path, verbose=args.verbose, background_color=color, background_image=background, only_depths=depths, movie_transform=transform))
  File "D:\Konami Data Tools\Servers\bemaniutils\bemani\format\afp\render.py", line 342, in render_path
    yield from self.__render(swf, only_depths, movie_transform, background_image)
  File "D:\Konami Data Tools\Servers\bemaniutils\bemani\format\afp\render.py", line 1225, in __render
    curimage = self.__render_object(curimage, root_clip, movie_transform, movie_mask, actual_mult_color, actual_add_color, actual_blend, only_depths=only_depths)
  File "D:\Konami Data Tools\Servers\bemaniutils\bemani\format\afp\render.py", line 857, in __render_object
    img = self.__render_object(img, obj, transform, mask, mult_color, add_color, blend, only_depths=new_only_depths, prefix=prefix + " ")
  File "D:\Konami Data Tools\Servers\bemaniutils\bemani\format\afp\render.py", line 857, in __render_object
    img = self.__render_object(img, obj, transform, mask, mult_color, add_color, blend, only_depths=new_only_depths, prefix=prefix + " ")
  File "D:\Konami Data Tools\Servers\bemaniutils\bemani\format\afp\render.py", line 857, in __render_object
    img = self.__render_object(img, obj, transform, mask, mult_color, add_color, blend, only_depths=new_only_depths, prefix=prefix + " ")
  [Previous line repeated 1 more time]
  File "D:\Konami Data Tools\Servers\bemaniutils\bemani\format\afp\render.py", line 918, in __render_object
    img = affine_composite(img, add_color, mult_color, transform, mask, blend, texture, single_threaded=self.__single_threaded)
  File "D:\Konami Data Tools\Servers\bemaniutils\bemani\format\afp\blend.py", line 244, in affine_composite
    proc.start()
  File "C:\Users\Cam\AppData\Local\Programs\Python\Python39\lib\multiprocessing\process.py", line 121, in start
    self._popen = self._Popen(self)
  File "C:\Users\Cam\AppData\Local\Programs\Python\Python39\lib\multiprocessing\context.py", line 224, in _Popen
    return _default_context.get_context().Process._Popen(process_obj)
  File "C:\Users\Cam\AppData\Local\Programs\Python\Python39\lib\multiprocessing\context.py", line 327, in _Popen
    return Popen(process_obj)
  File "C:\Users\Cam\AppData\Local\Programs\Python\Python39\lib\multiprocessing\popen_spawn_win32.py", line 45, in __init__
    prep_data = spawn.get_preparation_data(process_obj._name)
  File "C:\Users\Cam\AppData\Local\Programs\Python\Python39\lib\multiprocessing\spawn.py", line 154, in get_preparation_data
    _check_not_importing_main()
  File "C:\Users\Cam\AppData\Local\Programs\Python\Python39\lib\multiprocessing\spawn.py", line 134, in _check_not_importing_main
    raise RuntimeError('''
RuntimeError:
        An attempt has been made to start a new process before the
        current process has finished its bootstrapping phase.

        This probably means that you are not using fork to start your
        child processes and you have forgotten to use the proper idiom
        in the main module:

            if __name__ == '__main__':
                freeze_support()
                ...

        The "freeze_support()" line can be omitted if the program
        is not going to be frozen to produce an executable.
        ```

**Comment by DragonMinded** [comment]
That crash is baffling, because I already wrap my execution in a `if __name_ == '__main__':` section, and adding `freeze_support()` doesn't change anything. Note that there is a `--disable-threads` option and when I run with that, it does render on windows. It should also not have a problem if the cython was compiled since it uses threads instead of processes (thanks Python GIL).

**Comment by DragonMinded** [comment]
Also, in terms of what is and isn't AP2: I haven't found a game yet that doesn't use AP2 as its texture/animation format. It seems to be the common one used in everything. Older games use a TXP2 container, newer games use an IFS container, but they all use AP2 for everything.

**Comment by camprevail** [comment]
Ah ok, I thought you meant that you had never seen AP2 before. I guess you meant you've never seen the 0x83 tag then.

**Comment by DragonMinded** [comment]
AP2 is the informal name of the SWF-derivative that's used with libafp.dll/afp-core.dll and friends. There are a lot of tags, one of them being `AP2_IMAGE` which I've not seen before, though I know of its existence. I never bothered implementing anything that I hadn't seen since it couldn't be tested.

**Comment by DragonMinded** [comment]
Okay, give it a spin, there was a bunch of additions needed to support museca stuff. Word of caution, it looks like museca uses bytecode to infinite-loop some animations and we support said bytecode since its used in a lot of places to control sub-clip playback positioning. So if you render some stuff out of the box it will loop forever and you'll want to use `--only-frames 1-150` or something similar to render only the first 150 (or some other amount obviously) of frames.

**Comment by camprevail** [comment]
I think I understand. Ok, thanks! I'll see what happens!

**Comment by camprevail** [comment]
Alright, awesome! I got some animation! The random one I picked though was like 480 frames, so at first I only rendered 0-20 into a gif. That worked fine... but when I tried to render 0-100, I started getting errors about halfway through.
```
(environment) cam@ubuntu:~/bemaniutils$ python3 afputils render --path ms_sel_all --output test.gif --only-frames 0-100
pix_ms_sel.ifs
WARNING: Tried to call stop(PlacedClip(object_id=480, depth=4, source=RegisteredClip(tag_id=270), frame=20, total_frames=480, finished=False)) on <bemani.format.afp.render.AEPLib object at 0x7fa802e814c0> but that method doesn't exist!
WARNING: Tried to call deepGotoAndPlay(PlacedClip(object_id=480, depth=15, source=RegisteredClip(tag_id=231), frame=50, total_frames=480, finished=False), 'not_select_loop') on <bemani.format.afp.render.AEPLib object at 0x7fa802e7efd0> but that method doesn't exist!
WARNING: Tried to call deepGotoAndPlay(PlacedClip(object_id=480, depth=14, source=RegisteredClip(tag_id=231), frame=50, total_frames=480, finished=False), 'not_select_loop') on <bemani.format.afp.render.AEPLib object at 0x7fa802e7e8b0> but that method doesn't exist!
# repeats...
```

**Comment by camprevail** [comment]
Got a `WARNING: Unhandled PLACE_CAMERA tag!` error on some files in pix_common.ifs.

And also, a lot of these files stumble at something like "Cannot find texture reference x!" - where the texture is in like a region-specific ifs file, such as pix_common_j.ifs. Was wondering if maybe you have a way or can think of a way in the future to handle those.

**Comment by DragonMinded** [comment]
Are the region-specific ifs files delta ifs files that load the original when parsed? If so, it might just work if you give the renderer just the region-specific ifs. Otherwise, the renderer takes a list of input paths to load data from, so you would give the same `--path` argument, but you would specify both ifs files. It *should* load the textures from both and work.

**Comment by DragonMinded** [comment]
I figured out the windows multiprocessing crash, it had to do with the way my wrapper scripts worked. However, it seems that it is still bugged in some manner as the single-threaded python code is faster than multithreaded on Windows. Oh well, at least it works. I'll look at the bytecode issues in pix_ms_sel.ifs. Were you able to try to providing multiple ifs files to the renderer?

**Comment by camprevail** [comment]
Yeah, just tried it with pix_demo.ifs and pix_demo_j.ifs (using path `demo_all`) and was able to pretty closely render the title screen animation! 
I was also wondering, is there a way to list the supposed number of frames for a path? Would be useful for rendering to limit the frames if you know it's going to be a large number.

**Comment by DragonMinded** [comment]
It wouldn't be that difficult to add something like that in. We already have the basic info for SWFs when we call 'list'.

**Comment by DragonMinded** [comment]
Okay, I refactored the way out of hand afputils CLI tool and added options to the `list` command to display size and frame count. I also disabled loading textures and shapes when listing which speeds it up a bit.

**Comment by camprevail** [comment]
Thanks. Just tested, looks good!

**Comment by DragonMinded** [comment]
Closing this since there doesn't seem to be any more actionable things to address. Feel free to open additional bug reports with new problems.
