### ISSUE TITLE
afputils decompile crash

### ISSUE THREAD

**Issue by camprevail** [DragonMinded/bemaniutils#43]
```bash
(environment) cam@ubuntu:~/bemaniutils$ python3 afputils decompile -d museca/decompiled museca/pix_promo_ifs/afp/pass_promo_all museca/pix_promo_ifs/afp/bsi/pass_promo_all
Traceback (most recent call last):
  File "afputils", line 11, in <module>
    runpy.run_module(f"bemani.utils.{name}", run_name="__main__")
  File "/usr/lib/python3.8/runpy.py", line 210, in run_module
    return _run_code(code, {}, init_globals, run_name, mod_spec)
  File "/usr/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/home/cam/bemaniutils/bemani/utils/afputils.py", line 1262, in <module>
    sys.exit(main())
  File "/home/cam/bemaniutils/bemani/utils/afputils.py", line 1230, in main
    return decompile_afp(args.afp, args.bsi, args.directory, decompile_bytecode=args.decompile_bytecode, verbose=args.verbose)
AttributeError: 'Namespace' object has no attribute 'decompile_bytecode'
```

**Comment by DragonMinded** [comment]
LOL https://github.com/DragonMinded/bemaniutils/commit/b56481ca068f26c0cec2adee35287693a6bffe38

try now -_-;

**Comment by camprevail** [comment]
Lol works now, thanks.
