### ISSUE TITLE
Afputils error

### ISSUE THREAD

**Issue by camprevail** [DragonMinded/bemaniutils#76]
Sounds like konami may have added some new stuff to their afp lib. Tried to render the title scene from sdvx exceed gear season 2, datecode of 2022083000. Here's the end of the verbose log
```
Added gradation_darkblue_i_feb to animation texture library.
Added hit_mark_i_feb to animation texture library.
Added spark3_i_feb to animation texture library.
Added grace_in to animation library.
Traceback (most recent call last):
  File "afputils", line 11, in <module>
    runpy.run_module(f"bemani.utils.{name}", run_name="__main__")
  File "/usr/lib/python3.8/runpy.py", line 210, in run_module
    return _run_code(code, {}, init_globals, run_name, mod_spec)
  File "/usr/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/home/cam/bemaniutils/bemani/utils/afputils.py", line 1265, in <module>
    sys.exit(main())
  File "/home/cam/bemaniutils/bemani/utils/afputils.py", line 1239, in main
    return render_path(
  File "/home/cam/bemaniutils/bemani/utils/afputils.py", line 584, in render_path
    load_containers(renderer, containers, need_extras=True, verbose=verbose)
  File "/home/cam/bemaniutils/bemani/utils/afputils.py", line 468, in load_containers
    renderer.add_shape(shapename, shape)
  File "/home/cam/bemaniutils/bemani/format/afp/render.py", line 562, in add_shape
    data.parse()
  File "/home/cam/bemaniutils/bemani/format/afp/geo.py", line 86, in parse
    raise Exception(f"Unexpected file flags {fileflags} in GE2D structure!")
Exception: Unexpected file flags 36 in GE2D structure!
```

**Comment by DragonMinded** [comment]
I've run into that before, I think when I RE'd it I'd only ever seen 0x00 in the flags. So I put that assert in. I've seen this with flags 0x01 before but not 0x24. You can try commenting out the exception and seeing if it doesn't render, I still don't know what's up there.

**Comment by camprevail** [comment]
ah ok. I'll try it

**Comment by camprevail** [comment]
That worked, thanks!
